### ISSUE TITLE
using tmdbid or imdbid instead of best-guess match on the title

### ISSUE THREAD

**Issue by einsern** [mtimkovich/plex2letterboxd#13]
> Providing a LetterboxdURI, tmdbID or imdbID for each line in your file performs an exact match for the film (or diary entry, see below), while providing title (and optional year and director/s) results in a best-guess match.

from  https://letterboxd.com/about/importing-data/

Plex has both in ``items.guids`` 
You can see the format here:
https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.getGuid

All you have to do is filter out tmdb or imdb and you can still fall back to the title if you have to. 
Using those IDs seems way more efficient and less error prone.

**Comment by mtimkovich** [comment]
Sure, that seems easy enough to implement.

**Comment by mtimkovich** [comment]
9b8e4301ce03f4684deaa258c1e2a9dfe80413c3
