### ISSUE TITLE
Failing to run with Stacktrace

### ISSUE THREAD

**Issue by supawiz6991** [mtimkovich/plex2letterboxd#5]
When I try to run the script the following stacktrace is generated:

`Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/plex2letterboxd/plex2letterboxd/__main__.py", line 4, in <module>
    plex2letterboxd.main()
  File "/opt/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 58, in main
    plex = PlexServer(auth['baseurl'], auth['token'])
  File "/usr/local/lib64/python3.6/site-packages/plexapi/server.py", line 113, in __init__
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/plexapi/server.py", line 535, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 40, column 2
`
System Information:
OS: RHEL8
Python Version: 3.6.8

**Comment by mtimkovich** [comment]
Does this still happen for you? What's your plex's version?

**Comment by supawiz6991** [comment]
Hi,
Thanks for the follow up. I'm not sure what version of plex I was on when I originally made this, so I setup plex2letterboxd and tried again.
System information is the same as the previous test.
Plex is being run as a docker container in unraid (this was true for the first test as well). 
Current Plex server version shows: 1.26.0.5715

plex2letterboxd was able to run and did not generate the stacktrace but seems to only grab a maximum of 133 movies before ending, yet my library has 594 movies. Is this a limitation of plex2letterboxd? I don't see any indication of plex dropping the connection.

**Comment by supawiz6991** [comment]
Update: I figured out why I'm only seeing 133 out of 594 movies and that is because by default the script only exports movies that have been watched to the .csv file. Marking the videos as played gets them added to the .csv.

As my issue seems to be resolved at this point I'll go ahead and close the ticket.

Thanks!
