### ISSUE TITLE
Ability to export unwatched movies to watchlist?

### ISSUE THREAD

**Issue by sylvain-lec** [mtimkovich/plex2letterboxd#6]
Hello,
Thanks a lot for this tool.
I would like to use it to import the movies I didn’t see (stored on my plex server) in my Letterboxd watchlist but I sadly don’t know how to code this alternative use.
Could you by any chance point me in the right direction?

Thanks in advance!

**Comment by mtimkovich** [comment]
Sorry for taking so long to respond! I didn't see any of the notifications for this repo for some reason.

This is actually pretty easy to do. You're going to change this line: 

https://github.com/mtimkovich/plex2letterboxd/blob/b88d9147b3c07be8efac0d21a535c2a75c983b7e/plex2letterboxd/plex2letterboxd.py#L44

to `unwatched=True` to generate a list of your unwatched films and you can upload to your watchlist here: https://letterboxd.com/watchlist/
